FROM docker.elastic.co/elasticsearch/elasticsearch:8.14.3

# nori-analyzer 플러그인 설치
RUN elasticsearch-plugin install analysis-nori

# 환경 변수 설정
ENV discovery.type=single-node \
    network.host=0.0.0.0 \
    xpack.security.enabled=false \
    ELASTIC_PASSWORD=elastic \
    xpack.security.http.ssl.enabled=false \
    xpack.security.transport.ssl.enabled=false