server:
  port: 8083
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/project_db?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
