server:
  port: ${SERVER_PORT}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${S3_CREDENTIAL_ACCESS_KEY}
      secret-key: ${S3_CREDENTIAL_SECRET_KEY}
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  elasticsearch:
    rest:
      uris: http://${ES_URI}:9200
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_ENDPOINT}:3306/${DB_SCHEMA}?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
jwt:
  header: Authorization
  secret: ${JWT_TOKEN}
iamport:
  api-key: ${IAMPORT_API_KEY}
  secret-key: ${IAMPORT_SECRET_KEY}