server:
  port: 8083
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/project_db?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  header: Authorization
  secret: amlzZW9wLWNhcHN0b25lLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtamlzZW9wLWNhcHN0b25lLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
