name: Java CI/CD with Docker

on:
  push:
    branches: [ "main", "feature/deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      env:
        DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
        DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        S3_CREDENTIAL_ACCESS_KEY: ${{ secrets.S3_CREDENTIAL_ACCESS_KEY }}
        S3_CREDENTIAL_SECRET_KEY: ${{ secrets.S3_CREDENTIAL_SECRET_KEY }}
        ES_URI: ${{ secrets.ES_URI }}
        ES_USERNAME: ${{ secrets.ES_USERNAME }}
        ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
        ES_SSL_REFERENCE: ${{ secrets.ES_SSL_REFERENCE }}
        IAMPORT_API_KEY: ${{ secrets.IAMPORT_API_KEY }}
        IAMPORT_SECRET_KEY: ${{ secrets.IAMPORT_SECRET_KEY }}

    - name: Create env file
      run: |
        echo DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} >> .env
        echo DB_SCHEMA=${{ secrets.DB_SCHEMA }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo JWT_TOKEN=${{ secrets.JWT_TOKEN }} >> .env
        echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> .env
        echo S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} >> .env
        echo S3_CREDENTIAL_ACCESS_KEY=${{ secrets.S3_CREDENTIAL_ACCESS_KEY }} >> .env
        echo S3_CREDENTIAL_SECRET_KEY=${{ secrets.S3_CREDENTIAL_SECRET_KEY }} >> .env
        echo ES_URI=${{ secrets.ES_URI }} >> .env
        echo ES_USERNAME=${{ secrets.ES_USERNAME }} >> .env
        echo ES_PASSWORD=${{ secrets.ES_PASSWORD }} >> .env
        echo ES_SSL_REFERENCE=${{ secrets.ES_SSL_REFERENCE }} >> .env
        echo IAMPORT_API_KEY=${{ secrets.IAMPORT_API_KEY }} >> .env
        echo IAMPORT_SECRET_KEY=${{ secrets.IAMPORT_SECRET_KEY }} >> .env

    ## 이미지 빌드 및 도커허브에 push
    - name: server docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}/reservation-server .
        docker push ${{ secrets.DOCKER_REPO }}/reservation-server

    - name: nginx docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -f Dockerfile-nginx -t ${{ secrets.DOCKER_REPO }}/reservation-nginx .
        docker push ${{ secrets.DOCKER_REPO }}/reservation-nginx


    - name: Copy docker-compose.yaml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        source: "/github/workspace/docker-compose.yaml"
        target: "/home/ubuntu/"

    - name: Copy .env to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        source: "/github/workspace/.env"
        target: "/home/ubuntu/"

    ## docker compose up
    # HOST : 인스턴스 주소
    # KEY : rsa - 전부 복사, % 제외
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_REPO }}/reservation-server
          sudo docker pull ${{ secrets.DOCKER_REPO }}/reservation-nginx
          sudo docker-compose -f /home/ubuntu/github/workspace/docker-compose.yaml down
          sudo docker-compose -f /home/ubuntu/github/workspace/docker-compose.yaml up -d --force-recreate
          sudo docker image prune -f
    
